# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "cocoapods", "~> 1.8"

gem "fastlane", "~> 2.140"

gem "xcode-install", "~> 2.6"
